/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface CollateralReservationsFacetContract
  extends Truffle.Contract<CollateralReservationsFacetInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<CollateralReservationsFacetInstance>;
}

export interface CollateralReserved {
  name: "CollateralReserved";
  args: {
    agentVault: string;
    minter: string;
    collateralReservationId: BN;
    valueUBA: BN;
    feeUBA: BN;
    firstUnderlyingBlock: BN;
    lastUnderlyingBlock: BN;
    lastUnderlyingTimestamp: BN;
    paymentAddress: string;
    paymentReference: string;
    executor: string;
    executorFeeNatWei: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
    6: BN;
    7: BN;
    8: string;
    9: string;
    10: string;
    11: BN;
  };
}

type AllEvents = CollateralReserved;

export interface CollateralReservationsFacetInstance
  extends Truffle.ContractInstance {
  collateralReservationFee(
    _lots: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  reserveCollateral: {
    (
      _agentVault: string,
      _lots: number | BN | string,
      _maxMintingFeeBIPS: number | BN | string,
      _executor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _agentVault: string,
      _lots: number | BN | string,
      _maxMintingFeeBIPS: number | BN | string,
      _executor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
    sendTransaction(
      _agentVault: string,
      _lots: number | BN | string,
      _maxMintingFeeBIPS: number | BN | string,
      _executor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _agentVault: string,
      _lots: number | BN | string,
      _maxMintingFeeBIPS: number | BN | string,
      _executor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    collateralReservationFee(
      _lots: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    reserveCollateral: {
      (
        _agentVault: string,
        _lots: number | BN | string,
        _maxMintingFeeBIPS: number | BN | string,
        _executor: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _agentVault: string,
        _lots: number | BN | string,
        _maxMintingFeeBIPS: number | BN | string,
        _executor: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<BN>;
      sendTransaction(
        _agentVault: string,
        _lots: number | BN | string,
        _maxMintingFeeBIPS: number | BN | string,
        _executor: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _agentVault: string,
        _lots: number | BN | string,
        _maxMintingFeeBIPS: number | BN | string,
        _executor: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
