/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Truffle } from "./types";

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface FtsoV2PriceStoreProxyContract
  extends Truffle.Contract<FtsoV2PriceStoreProxyInstance> {
  "new"(
    _implementationAddress: string,
    _governanceSettings: string,
    _initialGovernance: string,
    _addressUpdater: string,
    _firstVotingRoundStartTs: number | BN | string,
    _votingEpochDurationSeconds: number | BN | string,
    _ftsoProtocolId: number | BN | string,
    meta?: Truffle.TransactionDetails
  ): Promise<FtsoV2PriceStoreProxyInstance>;
}

export interface AdminChanged {
  name: "AdminChanged";
  args: {
    previousAdmin: string;
    newAdmin: string;
    0: string;
    1: string;
  };
}

export interface BeaconUpgraded {
  name: "BeaconUpgraded";
  args: {
    beacon: string;
    0: string;
  };
}

export interface Upgraded {
  name: "Upgraded";
  args: {
    implementation: string;
    0: string;
  };
}

export type AllEvents = AdminChanged | BeaconUpgraded | Upgraded;

export interface FtsoV2PriceStoreProxyInstance
  extends Truffle.ContractInstance {
  methods: {};

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
