/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface MaliciousRewardManagerContract
  extends Truffle.Contract<MaliciousRewardManagerInstance> {
  "new"(
    _claim: number | BN | string,
    meta?: Truffle.TransactionDetails
  ): Promise<MaliciousRewardManagerInstance>;
}

type AllEvents = never;

export interface MaliciousRewardManagerInstance
  extends Truffle.ContractInstance {
  amount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  claim: {
    (
      arg0: string,
      arg1: string,
      arg2: number | BN | string,
      arg3: boolean,
      arg4: {
        merkleProof: string[];
        body: {
          rewardEpochId: number | BN | string;
          beneficiary: string;
          amount: number | BN | string;
          claimType: number | BN | string;
        };
      }[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      arg0: string,
      arg1: string,
      arg2: number | BN | string,
      arg3: boolean,
      arg4: {
        merkleProof: string[];
        body: {
          rewardEpochId: number | BN | string;
          beneficiary: string;
          amount: number | BN | string;
          claimType: number | BN | string;
        };
      }[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
    sendTransaction(
      arg0: string,
      arg1: string,
      arg2: number | BN | string,
      arg3: boolean,
      arg4: {
        merkleProof: string[];
        body: {
          rewardEpochId: number | BN | string;
          beneficiary: string;
          amount: number | BN | string;
          claimType: number | BN | string;
        };
      }[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      arg0: string,
      arg1: string,
      arg2: number | BN | string,
      arg3: boolean,
      arg4: {
        merkleProof: string[];
        body: {
          rewardEpochId: number | BN | string;
          beneficiary: string;
          amount: number | BN | string;
          claimType: number | BN | string;
        };
      }[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    amount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    claim: {
      (
        arg0: string,
        arg1: string,
        arg2: number | BN | string,
        arg3: boolean,
        arg4: {
          merkleProof: string[];
          body: {
            rewardEpochId: number | BN | string;
            beneficiary: string;
            amount: number | BN | string;
            claimType: number | BN | string;
          };
        }[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        arg0: string,
        arg1: string,
        arg2: number | BN | string,
        arg3: boolean,
        arg4: {
          merkleProof: string[];
          body: {
            rewardEpochId: number | BN | string;
            beneficiary: string;
            amount: number | BN | string;
            claimType: number | BN | string;
          };
        }[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<BN>;
      sendTransaction(
        arg0: string,
        arg1: string,
        arg2: number | BN | string,
        arg3: boolean,
        arg4: {
          merkleProof: string[];
          body: {
            rewardEpochId: number | BN | string;
            beneficiary: string;
            amount: number | BN | string;
            claimType: number | BN | string;
          };
        }[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        arg0: string,
        arg1: string,
        arg2: number | BN | string,
        arg3: boolean,
        arg4: {
          merkleProof: string[];
          body: {
            rewardEpochId: number | BN | string;
            beneficiary: string;
            amount: number | BN | string;
            claimType: number | BN | string;
          };
        }[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
