/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface MathUtilsMockContract
  extends Truffle.Contract<MathUtilsMockInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<MathUtilsMockInstance>;
}

type AllEvents = never;

export interface MathUtilsMockInstance extends Truffle.ContractInstance {
  mixedLTE_iu(
    _a: number | BN | string,
    _b: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  mixedLTE_ui(
    _a: number | BN | string,
    _b: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  positivePart(
    _x: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  roundUp(
    x: number | BN | string,
    rounding: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  subOrZero(
    _a: number | BN | string,
    _b: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  methods: {
    mixedLTE_iu(
      _a: number | BN | string,
      _b: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    mixedLTE_ui(
      _a: number | BN | string,
      _b: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    positivePart(
      _x: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    roundUp(
      x: number | BN | string,
      rounding: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    subOrZero(
      _a: number | BN | string,
      _b: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
