enableGlobalCache: true

nodeLinker: node-modules

nmMode: hardlinks-global

nmHoistingLimits: workspaces

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

preferAggregateCacheInfo: true

checksumBehavior: throw

logFilters:
  - # change "invalid checksum" from error to warning (yarn sometimes calculates checksums differently on Windows and Linux)
    code: YN0018
    level: warning

yarnPath: .yarn/releases/yarn-3.6.4.cjs
