enableGlobalCache: true

nodeLinker: node-modules

nmMode: hardlinks-global

nmHoistingLimits: workspaces

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

preferAggregateCacheInfo: true

checksumBehavior: update

yarnPath: .yarn/releases/yarn-3.6.4.cjs
